### ISSUE TITLE
[Feature Request] Add an image resize feature.

### ISSUE THREAD

**Issue by ghost** [icequeen3104/neelKanth#1]
Hi there ! Kudos on making your first repository !
I was going through and testing your code, when I noticed that there is no image resize function. 
**This causes a problem:** when the image resolution is too big, it won't fit on the monitor screen. This can become quite annoying. 
It'd be nice to add that feature to your code :)

**Comment by ghost** [comment]
Opened a pull request for this. Please check it out !

**Comment by icequeen3104** [comment]
> Hi there ! Kudos on making your first repository ! I was going through and testing your code, when I noticed that there is no image resize function. **This causes a problem:** when the image resolution is too big, it won't fit on the monitor screen. This can become quite annoying. It'd be nice to add that feature to your code :)

ok

**Comment by icequeen3104** [comment]
Thank you!!**Mr. Not so nerd** for your idea. I am updating the changes right away.
@ITnerd1

**Comment by ITnerd1** [comment]
Thanks to you !! **Ms. IceQueen** ! 
But there is a small issue. I noticed that you replaced the `res` variable in both `fx` and `fy` to a fixed `0.5` value.
 **This essentially breaks my implementation**. 
Since the fx and fy values are already set to 0.5, thus what resolution the user inputs does not matter unless you **change both fx and fy back to the res variable** (where the user input is stored). 
Please look into this.

**Comment by ghost** [comment]
Thanks to you !! **Ms. IceQueen** (¬‿¬)
